version: '3.6'
services:
  nginx-setup:
    container_name: nginx-setup
    image: "metadatacenter/cedar-nginx-setup:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-nginx-setup
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NGINX_HTTP_PORT}:80
    volumes:
      - nginx_log:/etc/nginx/log
      - cedar_cert:/etc/letsencrypt
    environment:
      - CEDAR_HOST

networks:
  cedarnet:
    external:
      name: cedarnet

volumes:
  cedar_cert:
    name: cedar_cert