version: '3'
services:
  editor:
    container_name: editor
    image: "metadatacenter/cedar-editor"
    build: ../../cedar-docker-build/cedar-editor
    networks:
      - cedarnet
    ports:
      - "${CEDAR_FRONTEND_PORT}:4200"
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/editor:/log
    environment:
      - CEDAR_HOST

networks:
  cedarnet:
    external:
      name: cedarnet