version: '3.6'
services:
  editor:
    container_name: editor
    image: "metadatacenter/cedar-editor:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-editor
    networks:
      - cedarnet
    ports:
      - "${CEDAR_FRONTEND_PORT}:4200"
    volumes:
      - frontend_log:/log
    environment:
      - CEDAR_HOST

networks:
  cedarnet:
    external:
      name: cedarnet

volumes:
  frontend_log:
    name: frontend_log
