version: '3'
services:
  cedar-microservice:
    container_name: cedar-microservice
    image: "metadatacenter/cedar-microservice:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-microservice
  schema-server:
    depends_on:
        - cedar-microservice
    container_name: schema-server
    image: "metadatacenter/cedar-schema-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-schema-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_SCHEMA_HTTP_PORT}:9003"
      - "${CEDAR_SCHEMA_ADMIN_PORT}:9103"
      - "${CEDAR_SCHEMA_STOP_PORT}:9203"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-schema-server/:/cedar/log/cedar-schema-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
  user-server:
    depends_on:
        - cedar-microservice
    container_name: user-server
    image: "metadatacenter/cedar-user-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-user-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_USER_HTTP_PORT}:9005"
      - "${CEDAR_USER_ADMIN_PORT}:9105"
      - "${CEDAR_USER_STOP_PORT}:9205"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-user-server/:/cedar/log/cedar-user-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
  submission-server:
    depends_on:
        - cedar-microservice
    container_name: submission-server
    image: "metadatacenter/cedar-submission-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-submission-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_SUBMISSION_HTTP_PORT}:9010"
      - "${CEDAR_SUBMISSION_ADMIN_PORT}:9110"
      - "${CEDAR_SUBMISSION_STOP_PORT}:9210"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-submission-server/:/cedar/log/cedar-submission-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NCBI_SRA_FTP_PASSWORD
  group-server:
    depends_on:
        - cedar-microservice
    container_name: group-server
    image: "metadatacenter/cedar-group-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-group-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_GROUP_HTTP_PORT}:9009"
      - "${CEDAR_GROUP_ADMIN_PORT}:9109"
      - "${CEDAR_GROUP_STOP_PORT}:9209"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-group-server/:/cedar/log/cedar-group-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
  workspace-server:
    depends_on:
        - cedar-microservice
    container_name: workspace-server
    image: "metadatacenter/cedar-workspace-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-workspace-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_WORKSPACE_HTTP_PORT}:9008"
      - "${CEDAR_WORKSPACE_ADMIN_PORT}:9108"
      - "${CEDAR_WORKSPACE_STOP_PORT}:9208"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-workspace-server/:/cedar/log/cedar-workspace-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_USER_PASSWORD
  template-server:
    depends_on:
        - cedar-microservice
    container_name: template-server
    image: "metadatacenter/cedar-template-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-template-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_TEMPLATE_HTTP_PORT}:9001"
      - "${CEDAR_TEMPLATE_ADMIN_PORT}:9101"
      - "${CEDAR_TEMPLATE_STOP_PORT}:9201"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-template-server/:/cedar/log/cedar-template-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_TEST_USER1_ID
  worker-server:
    depends_on:
        - cedar-microservice
    container_name: worker-server
    image: "metadatacenter/cedar-worker-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-worker-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_WORKER_HTTP_PORT}:9011"
      - "${CEDAR_WORKER_ADMIN_PORT}:9111"
      - "${CEDAR_WORKER_STOP_PORT}:9211"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-worker-server/:/cedar/log/cedar-worker-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
  valuerecommender-server:
    depends_on:
        - cedar-microservice
    container_name: valuerecommender-server
    image: "metadatacenter/cedar-valuerecommender-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-valuerecommender-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_VALUERECOMMENDER_HTTP_PORT}:9006"
      - "${CEDAR_VALUERECOMMENDER_ADMIN_PORT}:9106"
      - "${CEDAR_VALUERECOMMENDER_STOP_PORT}:9206"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-valuerecommender-server/:/cedar/log/cedar-valuerecommender-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
  terminology-server:
    depends_on:
        - cedar-microservice
    container_name: terminology-server
    image: "metadatacenter/cedar-terminology-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-terminology-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_TERMINOLOGY_HTTP_PORT}:9004"
      - "${CEDAR_TERMINOLOGY_ADMIN_PORT}:9104"
      - "${CEDAR_TERMINOLOGY_STOP_PORT}:9204"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-terminology-server/:/cedar/log/cedar-terminology-server/
      - ${CEDAR_DOCKER_DATA_HOME}/cache/terminology/:/cedar/cache/terminology/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_BIOPORTAL_API_KEY
      - CEDAR_BIOPORTAL_REST_BASE
      - CEDAR_TEST_USER1_ID
  repo-server:
    depends_on:
        - cedar-microservice
    container_name: repo-server
    image: "metadatacenter/cedar-repo-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-repo-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_REPO_HTTP_PORT}:9002"
      - "${CEDAR_REPO_ADMIN_PORT}:9102"
      - "${CEDAR_REPO_STOP_PORT}:9202"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-repo-server/:/cedar/log/cedar-repo-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
  resource-server:
    depends_on:
        - cedar-microservice
    container_name: resource-server
    image: "metadatacenter/cedar-resource-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-resource-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_RESOURCE_HTTP_PORT}:9007"
      - "${CEDAR_RESOURCE_ADMIN_PORT}:9107"
      - "${CEDAR_RESOURCE_STOP_PORT}:9207"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-resource-server/:/cedar/log/cedar-resource-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_SALT_API_KEY
      - CEDAR_ELASTICSEARCH_HOST
      - CEDAR_ELASTICSEARCH_TRANSPORT_PORT
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
  messaging-server:
    depends_on:
        - cedar-microservice
    container_name: messaging-server
    image: "metadatacenter/cedar-messaging-server:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-messaging-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_MESSAGING_HTTP_PORT}:9012"
      - "${CEDAR_MESSAGING_ADMIN_PORT}:9112"
      - "${CEDAR_MESSAGING_STOP_PORT}:9212"
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/cedar-messaging-server/:/cedar/log/cedar-messaging-server/
      - ${CEDAR_DOCKER_CA_HOME}/:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_MESSAGING_MYSQL_HOST
      - CEDAR_MESSAGING_MYSQL_PORT
      - CEDAR_MESSAGING_MYSQL_DB
      - CEDAR_MESSAGING_MYSQL_USER
      - CEDAR_MESSAGING_MYSQL_PASSWORD
      - CEDAR_TEST_USER1_ID
      - CEDAR_TEST_USER2_ID

networks:
  cedarnet:
    external:
      name: cedarnet