version: '3'
services:
  mysql:
    container_name: mysql
    image: "metadatacenter/cedar-mysql:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-mysql
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KEYCLOAK_MYSQL_PORT}:3306
    volumes:
      - ${CEDAR_DOCKER_DATA_HOME}/mysql/:/var/lib/mysql
      - ${CEDAR_DOCKER_LOG_HOME}/mysql/:/var/log/mysql
    environment:
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_NET_GATEWAY

  mongo:
    container_name: mongo
    image: "metadatacenter/cedar-mongo:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-mongo
    networks:
      - cedarnet
    ports:
      - "${CEDAR_MONGO_PORT}:27017"
    volumes:
      - ${CEDAR_DOCKER_DATA_HOME}/mongo/:/data/db
      - ${CEDAR_DOCKER_LOG_HOME}/mongo/:/data/log
    environment:
      - CEDAR_MONGO_ROOT_USER_NAME
      - CEDAR_MONGO_ROOT_USER_PASSWORD
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_HOST
      - CEDAR_ADMIN_USER_API_KEY

  redis-persistent:
    container_name: redis-persistent
    image: "metadatacenter/cedar-redis-persistent:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-redis-persistent
    networks:
      - cedarnet
    ports:
      - ${CEDAR_REDIS_PERSISTENT_PORT}:6379
    volumes:
      - ${CEDAR_DOCKER_DATA_HOME}/redis/:/data
      - ${CEDAR_DOCKER_LOG_HOME}/redis/:/log
    sysctls:
      - net.core.somaxconn=512

  elasticsearch:
    container_name: elasticsearch
    image: "metadatacenter/cedar-elasticsearch:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-elasticsearch
    networks:
      - cedarnet
    ports:
      - ${CEDAR_ELASTICSEARCH_REST_PORT}:9200
      - ${CEDAR_ELASTICSEARCH_TRANSPORT_PORT}:9300
    volumes:
      - ${CEDAR_DOCKER_DATA_HOME}/elasticsearch:/usr/share/elasticsearch/data
      - ${CEDAR_DOCKER_LOG_HOME}/elasticsearch:/usr/share/elasticsearch/logs

  neo4j:
    container_name: neo4j
    image: "metadatacenter/cedar-neo4j:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-neo4j
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NEO4J_REST_PORT}:7474
      - ${CEDAR_NEO4J_BOLT_PORT}:7687
    volumes:
      - ${CEDAR_DOCKER_DATA_HOME}/neo4j/:/data
      - ${CEDAR_DOCKER_LOG_HOME}/neo4j/:/logs
    environment:
      - CEDAR_NEO4J_USER_PASSWORD

  keycloak:
    container_name: keycloak
    image: "metadatacenter/cedar-keycloak:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-keycloak
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KEYCLOAK_PORT}:8080
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/keycloak:/opt/jboss/keycloak/standalone/log
    environment:
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_KEYCLOAK_MYSQL_USER
      - CEDAR_KEYCLOAK_MYSQL_PASSWORD
      - CEDAR_KEYCLOAK_MYSQL_PORT
      - CEDAR_KEYCLOAK_MYSQL_HOST
      - CEDAR_KEYCLOAK_MYSQL_DB
      - CEDAR_KEYCLOAK_ADMIN_USER
      - CEDAR_KEYCLOAK_ADMIN_PASSWORD
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_RESOURCE_HTTP_PORT

  nginx:
    container_name: nginx
    image: "metadatacenter/cedar-nginx:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-nginx
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NGINX_HTTP_PORT}:80
      - ${CEDAR_NGINX_HTTPS_PORT}:443
    volumes:
      - ${CEDAR_DOCKER_LOG_HOME}/:/etc/nginx/log
      - ${CEDAR_DOCKER_CERT_HOME}/:/usr/local/etc/certificates
    environment:
      - CEDAR_HOST
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_FRONTEND_HOST

networks:
  cedarnet:
    external:
      name: cedarnet