version: '3'
services:
  redis-commander:
    container_name: redis-commander
    image: "metadatacenter/cedar-redis-commander"
    build: ../../cedar-docker-build/cedar-redis-commander
    networks:
      - cedarnet
    ports:
      - "${CEDAR_REDIS_COMMANDER_PORT}:8081"
    environment:
      - CEDAR_NET_GATEWAY

  kibana:
    container_name: kibana
    image: "metadatacenter/cedar-kibana"
    build: ../../cedar-docker-build/cedar-kibana
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KIBANA_PORT}:5601


networks:
  cedarnet:
    external:
      name: cedarnet